name: Setup pnpm and Node.js for CI/CD
description: Setup pnpm and Node.js for CI/CD workflows

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '24'
    type: string
  pnpm-version:
    description: 'pnpm version to use'
    required: true
    default: '11'

outputs:
  node-version: "Node.js version"
  value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: "composite"
  steps:
   - name: Setup pnpm
     uses: pnpm/action-setup@v6
     with:
        version: ${{ inputs.pnpm-version }}   
        run_install: false

   - name: Setup pnpm
     uses: actions/setup-node@v6
     with:
        node-version: ${{ inputs.node-version }}
        run_install: false