name: Pruebas Playwright

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    frontend_lint:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install

    tests_playwright:
            runs-on: ubuntu-22.04

            steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '18'

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Corriendo las pruebas de Playwright
              run: npx playwright test