name: 04 Events

on:
   issues:
     types: [opened, reopened]
   issue_comment:
     types: [created]     

jobs:
    inspect_event:
        runs-on: ubuntu-22.04
        permissions:
          issues: write
          
        steps:
            - name: Mostrar evento
              run: |
                    echo "Evento: ${{ github.event_name }}"
                    echo "Acción: ${{ github.event.action }}"
                    echo "Número de issue: ${{ github.event.issue.number }}"
                    echo "Título de issue: ${{ github.event.issue.title }}"
                    echo "Comentario: ${{ github.event.comment.body }}"


            - name: Comentar como un bot en GitHub Actions
              if: github.event_name == 'issues' && github.event.action == 'opened'
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                GITHUB_REPOSITORY: ${{ github.repository }}
              run:
                gh issue comment $ISSUE_NUMBER --repo $GITHUB_REPOSITORY --body "¡Gracias por abrir este issue! Un bot de GitHub Actions ha respondido automáticamente."


            - name: Comentar como autor del repositorio en GitHub Actions
              if: github.event_name == 'issue_comment' && github.event.action == 'created'
              env:
                AUTHOR_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                ISSUE_NUMBER: ${{ github.event.issue.number }}
              run: |
               if [[ -z "$AUTHOR_TOKEN" ]]; then
                 echo "::warning::El token de acceso personal no está configurado. No se puede comentar como autor del repositorio."
                 exit 0
                fi
                GH_TOKEN="$AUTHOR_TOKEN" gh issue comment $ISSUE_NUMBER \
                --repo $GITHUB_REPOSITORY \
                --body "Hola, soy el autor del repositorio y he visto tu comentario. ¡Gracias por tu participación!"

                