name: Manual

on:
    workflow_dispatch:

jobs:
    manual:
        runs-on: ubuntu-22.04
        steps:
            - name: Pruebas Manuales
              run: echo "Ejecutando pruebas manuales"        

            - name: ver fecha y hora
              run: date
              
            - name: ver archivos disponibles
              run: ls -la  

