name: Playwright Tests

on:
    push:
        branches: [main]

jobs:
    playwright:
        runs-on: ubuntu-22.04
        steps:
            - name: Pruebas Playwirhgt
              run: echo "Ejecutando pruebas Playwright"

            - name: ver archivos disponibles
              run: ls -la

        
