name : 03 Schedule

on:
    schedule:
        - cron: '0 18 * * *' 
        - cron: '0 18 * * 1-5'

jobs:
    schedule:
        runs-on: ubuntu-22.04
        steps:
            - name: Ejecutar tareas programadas
              run: echo "Ejecutando tareas programadas a las 18:00 todos los"